apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcauthn.fullname" . }}-config
  labels:
  {{- include "vcauthn.labels" . | nindent 4 }}
type: Opaque
stringData:
  acapy-admin-api-key: {{ .Values.configuration.acapyAdminApiKey  | quote }}
  idenity-server-api-key: {{ .Values.configuration.identityServerApiKey  | quote }}
  postgresql-password: {{ .Values.configuration.postgresql.password  | quote }}
  postgresql-username: {{ .Values.configuration.postgresql.username  | quote }}