apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vc-authn.fullname" . }}
  labels:
  {{- include "vcauthn.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.controllerDbPvc.storageRequest | quote }}