apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcauthn.fullname" . }}-rsa
  labels:
  {{- include "vcauthn.labels" . | nindent 4 }}
stringData:
  secret-key.rsa: |
    $(cat ../keys/smart_keys | b64enc | quote)
type: Opaque